// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: protos/types/health.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_UNHEALTHY":   2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_health_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_protos_types_health_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_health_proto_rawDescGZIP(), []int{0}
}

type HealthConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Address       *Endpoint              `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthConfig) Reset() {
	*x = HealthConfig{}
	mi := &file_protos_types_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthConfig) ProtoMessage() {}

func (x *HealthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthConfig.ProtoReflect.Descriptor instead.
func (*HealthConfig) Descriptor() ([]byte, []int) {
	return file_protos_types_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthConfig) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthConfig) GetAddress() *Endpoint {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_protos_types_health_proto protoreflect.FileDescriptor

const file_protos_types_health_proto_rawDesc = "" +
	"\n" +
	"\x19protos/types/health.proto\x12\rlocator.types\x1a\x1bprotos/types/endpoint.proto\"[\n" +
	"\fHealthConfig\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x121\n" +
	"\aaddress\x18\x02 \x01(\v2\x17.locator.types.EndpointR\aaddress*e\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x02B+Z)github.com/hunkvm/locator/pkg/proto/typesb\x06proto3"

var (
	file_protos_types_health_proto_rawDescOnce sync.Once
	file_protos_types_health_proto_rawDescData []byte
)

func file_protos_types_health_proto_rawDescGZIP() []byte {
	file_protos_types_health_proto_rawDescOnce.Do(func() {
		file_protos_types_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_types_health_proto_rawDesc), len(file_protos_types_health_proto_rawDesc)))
	})
	return file_protos_types_health_proto_rawDescData
}

var file_protos_types_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_types_health_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_types_health_proto_goTypes = []any{
	(HealthStatus)(0),    // 0: locator.types.HealthStatus
	(*HealthConfig)(nil), // 1: locator.types.HealthConfig
	(*Endpoint)(nil),     // 2: locator.types.Endpoint
}
var file_protos_types_health_proto_depIdxs = []int32{
	2, // 0: locator.types.HealthConfig.address:type_name -> locator.types.Endpoint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_types_health_proto_init() }
func file_protos_types_health_proto_init() {
	if File_protos_types_health_proto != nil {
		return
	}
	file_protos_types_endpoint_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_types_health_proto_rawDesc), len(file_protos_types_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_types_health_proto_goTypes,
		DependencyIndexes: file_protos_types_health_proto_depIdxs,
		EnumInfos:         file_protos_types_health_proto_enumTypes,
		MessageInfos:      file_protos_types_health_proto_msgTypes,
	}.Build()
	File_protos_types_health_proto = out.File
	file_protos_types_health_proto_goTypes = nil
	file_protos_types_health_proto_depIdxs = nil
}
