// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: protos/types/service.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       *Endpoint              `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	HealthStatus  HealthStatus           `protobuf:"varint,5,opt,name=health_status,json=healthStatus,proto3,enum=locator.types.HealthStatus" json:"health_status,omitempty"`
	HealthCheck   *HealthConfig          `protobuf:"bytes,6,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastChecked   string                 `protobuf:"bytes,8,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	RegisteredAt  string                 `protobuf:"bytes,9,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_protos_types_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_protos_types_service_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetAddress() *Endpoint {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Service) GetHealthStatus() HealthStatus {
	if x != nil {
		return x.HealthStatus
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *Service) GetHealthCheck() *HealthConfig {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *Service) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Service) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Service) GetLastChecked() string {
	if x != nil {
		return x.LastChecked
	}
	return ""
}

func (x *Service) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

var File_protos_types_service_proto protoreflect.FileDescriptor

const file_protos_types_service_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/types/service.proto\x12\rlocator.types\x1a\x1bprotos/types/endpoint.proto\x1a\x19protos/types/health.proto\"\xc3\x03\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\aaddress\x18\x03 \x01(\v2\x17.locator.types.EndpointR\aaddress\x12@\n" +
	"\rhealth_status\x18\x05 \x01(\x0e2\x1b.locator.types.HealthStatusR\fhealthStatus\x12>\n" +
	"\fhealth_check\x18\x06 \x01(\v2\x1b.locator.types.HealthConfigR\vhealthCheck\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.locator.types.Service.MetadataEntryR\bmetadata\x12!\n" +
	"\flast_checked\x18\b \x01(\tR\vlastChecked\x12#\n" +
	"\rregistered_at\x18\t \x01(\tR\fregisteredAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B+Z)github.com/hunkvm/locator/pkg/proto/typesb\x06proto3"

var (
	file_protos_types_service_proto_rawDescOnce sync.Once
	file_protos_types_service_proto_rawDescData []byte
)

func file_protos_types_service_proto_rawDescGZIP() []byte {
	file_protos_types_service_proto_rawDescOnce.Do(func() {
		file_protos_types_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_types_service_proto_rawDesc), len(file_protos_types_service_proto_rawDesc)))
	})
	return file_protos_types_service_proto_rawDescData
}

var file_protos_types_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_types_service_proto_goTypes = []any{
	(*Service)(nil),      // 0: locator.types.Service
	nil,                  // 1: locator.types.Service.MetadataEntry
	(*Endpoint)(nil),     // 2: locator.types.Endpoint
	(HealthStatus)(0),    // 3: locator.types.HealthStatus
	(*HealthConfig)(nil), // 4: locator.types.HealthConfig
}
var file_protos_types_service_proto_depIdxs = []int32{
	2, // 0: locator.types.Service.address:type_name -> locator.types.Endpoint
	3, // 1: locator.types.Service.health_status:type_name -> locator.types.HealthStatus
	4, // 2: locator.types.Service.health_check:type_name -> locator.types.HealthConfig
	1, // 3: locator.types.Service.metadata:type_name -> locator.types.Service.MetadataEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_types_service_proto_init() }
func file_protos_types_service_proto_init() {
	if File_protos_types_service_proto != nil {
		return
	}
	file_protos_types_endpoint_proto_init()
	file_protos_types_health_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_types_service_proto_rawDesc), len(file_protos_types_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_types_service_proto_goTypes,
		DependencyIndexes: file_protos_types_service_proto_depIdxs,
		MessageInfos:      file_protos_types_service_proto_msgTypes,
	}.Build()
	File_protos_types_service_proto = out.File
	file_protos_types_service_proto_goTypes = nil
	file_protos_types_service_proto_depIdxs = nil
}
