// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: api/registry/registry.proto

package registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Selector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selector) Reset() {
	*x = Selector{}
	mi := &file_api_registry_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selector) ProtoMessage() {}

func (x *Selector) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selector.ProtoReflect.Descriptor instead.
func (*Selector) Descriptor() ([]byte, []int) {
	return file_api_registry_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Selector) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Selector) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RetrieveServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selectors     []*Selector            `protobuf:"bytes,1,rep,name=selectors,proto3" json:"selectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveServiceRequest) Reset() {
	*x = RetrieveServiceRequest{}
	mi := &file_api_registry_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveServiceRequest) ProtoMessage() {}

func (x *RetrieveServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveServiceRequest.ProtoReflect.Descriptor instead.
func (*RetrieveServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveServiceRequest) GetSelectors() []*Selector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

type RetrieveServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Services      []*Service             `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveServiceResponse) Reset() {
	*x = RetrieveServiceResponse{}
	mi := &file_api_registry_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveServiceResponse) ProtoMessage() {}

func (x *RetrieveServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveServiceResponse.ProtoReflect.Descriptor instead.
func (*RetrieveServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_registry_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetrieveServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RetrieveServiceResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type RegisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       *Endpoint              `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	HealthCheck   *HealthConfig          `protobuf:"bytes,3,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_api_registry_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_registry_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterServiceRequest) GetAddress() *Endpoint {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *RegisterServiceRequest) GetHealthCheck() *HealthConfig {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *RegisterServiceRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RegisterServiceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_api_registry_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_registry_registry_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterServiceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EnableServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selectors     []*Selector            `protobuf:"bytes,1,rep,name=selectors,proto3" json:"selectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableServiceRequest) Reset() {
	*x = EnableServiceRequest{}
	mi := &file_api_registry_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableServiceRequest) ProtoMessage() {}

func (x *EnableServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableServiceRequest.ProtoReflect.Descriptor instead.
func (*EnableServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_registry_proto_rawDescGZIP(), []int{5}
}

func (x *EnableServiceRequest) GetSelectors() []*Selector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

type EnableServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableServiceResponse) Reset() {
	*x = EnableServiceResponse{}
	mi := &file_api_registry_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableServiceResponse) ProtoMessage() {}

func (x *EnableServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableServiceResponse.ProtoReflect.Descriptor instead.
func (*EnableServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_registry_registry_proto_rawDescGZIP(), []int{6}
}

func (x *EnableServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnableServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DisableServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selectors     []*Selector            `protobuf:"bytes,1,rep,name=selectors,proto3" json:"selectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableServiceRequest) Reset() {
	*x = DisableServiceRequest{}
	mi := &file_api_registry_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableServiceRequest) ProtoMessage() {}

func (x *DisableServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableServiceRequest.ProtoReflect.Descriptor instead.
func (*DisableServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_registry_proto_rawDescGZIP(), []int{7}
}

func (x *DisableServiceRequest) GetSelectors() []*Selector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

type DisableServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableServiceResponse) Reset() {
	*x = DisableServiceResponse{}
	mi := &file_api_registry_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableServiceResponse) ProtoMessage() {}

func (x *DisableServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableServiceResponse.ProtoReflect.Descriptor instead.
func (*DisableServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_registry_registry_proto_rawDescGZIP(), []int{8}
}

func (x *DisableServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisableServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeregisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceRequest) Reset() {
	*x = DeregisterServiceRequest{}
	mi := &file_api_registry_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceRequest) ProtoMessage() {}

func (x *DeregisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceRequest.ProtoReflect.Descriptor instead.
func (*DeregisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_registry_proto_rawDescGZIP(), []int{9}
}

func (x *DeregisterServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeregisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceResponse) Reset() {
	*x = DeregisterServiceResponse{}
	mi := &file_api_registry_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceResponse) ProtoMessage() {}

func (x *DeregisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceResponse.ProtoReflect.Descriptor instead.
func (*DeregisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_registry_registry_proto_rawDescGZIP(), []int{10}
}

func (x *DeregisterServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeregisterServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_registry_registry_proto protoreflect.FileDescriptor

const file_api_registry_registry_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/registry/registry.proto\x12\alocator\x1a\x1aapi/registry/service.proto\"8\n" +
	"\bSelector\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"I\n" +
	"\x16RetrieveServiceRequest\x12/\n" +
	"\tselectors\x18\x01 \x03(\v2\x11.locator.SelectorR\tselectors\"{\n" +
	"\x17RetrieveServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\bservices\x18\x03 \x03(\v2\x10.locator.ServiceR\bservices\"\xb5\x02\n" +
	"\x16RegisterServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\aaddress\x18\x02 \x01(\v2\x11.locator.EndpointR\aaddress\x128\n" +
	"\fhealth_check\x18\x03 \x01(\v2\x15.locator.HealthConfigR\vhealthCheck\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12I\n" +
	"\bmetadata\x18\x05 \x03(\v2-.locator.RegisterServiceRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x17RegisterServiceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"G\n" +
	"\x14EnableServiceRequest\x12/\n" +
	"\tselectors\x18\x01 \x03(\v2\x11.locator.SelectorR\tselectors\"K\n" +
	"\x15EnableServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x15DisableServiceRequest\x12/\n" +
	"\tselectors\x18\x01 \x03(\v2\x11.locator.SelectorR\tselectors\"L\n" +
	"\x16DisableServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\x18DeregisterServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x19DeregisterServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa0\x03\n" +
	"\x16ServiceRegistryService\x12M\n" +
	"\bRetrieve\x12\x1f.locator.RetrieveServiceRequest\x1a .locator.RetrieveServiceResponse\x12M\n" +
	"\bRegister\x12\x1f.locator.RegisterServiceRequest\x1a .locator.RegisterServiceResponse\x12G\n" +
	"\x06Enable\x12\x1d.locator.EnableServiceRequest\x1a\x1e.locator.EnableServiceResponse\x12J\n" +
	"\aDisable\x12\x1e.locator.DisableServiceRequest\x1a\x1f.locator.DisableServiceResponse\x12S\n" +
	"\n" +
	"Deregister\x12!.locator.DeregisterServiceRequest\x1a\".locator.DeregisterServiceResponseB\x16Z\x14locator/api/registryb\x06proto3"

var (
	file_api_registry_registry_proto_rawDescOnce sync.Once
	file_api_registry_registry_proto_rawDescData []byte
)

func file_api_registry_registry_proto_rawDescGZIP() []byte {
	file_api_registry_registry_proto_rawDescOnce.Do(func() {
		file_api_registry_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_registry_registry_proto_rawDesc), len(file_api_registry_registry_proto_rawDesc)))
	})
	return file_api_registry_registry_proto_rawDescData
}

var file_api_registry_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_registry_registry_proto_goTypes = []any{
	(*Selector)(nil),                  // 0: locator.Selector
	(*RetrieveServiceRequest)(nil),    // 1: locator.RetrieveServiceRequest
	(*RetrieveServiceResponse)(nil),   // 2: locator.RetrieveServiceResponse
	(*RegisterServiceRequest)(nil),    // 3: locator.RegisterServiceRequest
	(*RegisterServiceResponse)(nil),   // 4: locator.RegisterServiceResponse
	(*EnableServiceRequest)(nil),      // 5: locator.EnableServiceRequest
	(*EnableServiceResponse)(nil),     // 6: locator.EnableServiceResponse
	(*DisableServiceRequest)(nil),     // 7: locator.DisableServiceRequest
	(*DisableServiceResponse)(nil),    // 8: locator.DisableServiceResponse
	(*DeregisterServiceRequest)(nil),  // 9: locator.DeregisterServiceRequest
	(*DeregisterServiceResponse)(nil), // 10: locator.DeregisterServiceResponse
	nil,                               // 11: locator.RegisterServiceRequest.MetadataEntry
	(*Service)(nil),                   // 12: locator.Service
	(*Endpoint)(nil),                  // 13: locator.Endpoint
	(*HealthConfig)(nil),              // 14: locator.HealthConfig
}
var file_api_registry_registry_proto_depIdxs = []int32{
	0,  // 0: locator.RetrieveServiceRequest.selectors:type_name -> locator.Selector
	12, // 1: locator.RetrieveServiceResponse.services:type_name -> locator.Service
	13, // 2: locator.RegisterServiceRequest.address:type_name -> locator.Endpoint
	14, // 3: locator.RegisterServiceRequest.health_check:type_name -> locator.HealthConfig
	11, // 4: locator.RegisterServiceRequest.metadata:type_name -> locator.RegisterServiceRequest.MetadataEntry
	0,  // 5: locator.EnableServiceRequest.selectors:type_name -> locator.Selector
	0,  // 6: locator.DisableServiceRequest.selectors:type_name -> locator.Selector
	1,  // 7: locator.ServiceRegistryService.Retrieve:input_type -> locator.RetrieveServiceRequest
	3,  // 8: locator.ServiceRegistryService.Register:input_type -> locator.RegisterServiceRequest
	5,  // 9: locator.ServiceRegistryService.Enable:input_type -> locator.EnableServiceRequest
	7,  // 10: locator.ServiceRegistryService.Disable:input_type -> locator.DisableServiceRequest
	9,  // 11: locator.ServiceRegistryService.Deregister:input_type -> locator.DeregisterServiceRequest
	2,  // 12: locator.ServiceRegistryService.Retrieve:output_type -> locator.RetrieveServiceResponse
	4,  // 13: locator.ServiceRegistryService.Register:output_type -> locator.RegisterServiceResponse
	6,  // 14: locator.ServiceRegistryService.Enable:output_type -> locator.EnableServiceResponse
	8,  // 15: locator.ServiceRegistryService.Disable:output_type -> locator.DisableServiceResponse
	10, // 16: locator.ServiceRegistryService.Deregister:output_type -> locator.DeregisterServiceResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_registry_registry_proto_init() }
func file_api_registry_registry_proto_init() {
	if File_api_registry_registry_proto != nil {
		return
	}
	file_api_registry_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_registry_registry_proto_rawDesc), len(file_api_registry_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_registry_registry_proto_goTypes,
		DependencyIndexes: file_api_registry_registry_proto_depIdxs,
		MessageInfos:      file_api_registry_registry_proto_msgTypes,
	}.Build()
	File_api_registry_registry_proto = out.File
	file_api_registry_registry_proto_goTypes = nil
	file_api_registry_registry_proto_depIdxs = nil
}
