// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: api/registry/service.proto

package registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_UNHEALTHY":   2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_registry_service_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_api_registry_service_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_registry_service_proto_rawDescGZIP(), []int{0}
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_api_registry_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_api_registry_service_proto_rawDescGZIP(), []int{0}
}

func (x *Endpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Endpoint) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type HealthConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Address       *Endpoint              `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthConfig) Reset() {
	*x = HealthConfig{}
	mi := &file_api_registry_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthConfig) ProtoMessage() {}

func (x *HealthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthConfig.ProtoReflect.Descriptor instead.
func (*HealthConfig) Descriptor() ([]byte, []int) {
	return file_api_registry_service_proto_rawDescGZIP(), []int{1}
}

func (x *HealthConfig) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthConfig) GetAddress() *Endpoint {
	if x != nil {
		return x.Address
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       *Endpoint              `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	HealthStatus  HealthStatus           `protobuf:"varint,5,opt,name=health_status,json=healthStatus,proto3,enum=locator.HealthStatus" json:"health_status,omitempty"`
	HealthCheck   *HealthConfig          `protobuf:"bytes,6,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastChecked   string                 `protobuf:"bytes,8,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	RegisteredAt  string                 `protobuf:"bytes,9,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_api_registry_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_api_registry_service_proto_rawDescGZIP(), []int{2}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetAddress() *Endpoint {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Service) GetHealthStatus() HealthStatus {
	if x != nil {
		return x.HealthStatus
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *Service) GetHealthCheck() *HealthConfig {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *Service) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Service) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Service) GetLastChecked() string {
	if x != nil {
		return x.LastChecked
	}
	return ""
}

func (x *Service) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

var File_api_registry_service_proto protoreflect.FileDescriptor

const file_api_registry_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/registry/service.proto\x12\alocator\"2\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"U\n" +
	"\fHealthConfig\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12+\n" +
	"\aaddress\x18\x02 \x01(\v2\x11.locator.EndpointR\aaddress\"\xab\x03\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\aaddress\x18\x03 \x01(\v2\x11.locator.EndpointR\aaddress\x12:\n" +
	"\rhealth_status\x18\x05 \x01(\x0e2\x15.locator.HealthStatusR\fhealthStatus\x128\n" +
	"\fhealth_check\x18\x06 \x01(\v2\x15.locator.HealthConfigR\vhealthCheck\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12:\n" +
	"\bmetadata\x18\a \x03(\v2\x1e.locator.Service.MetadataEntryR\bmetadata\x12!\n" +
	"\flast_checked\x18\b \x01(\tR\vlastChecked\x12#\n" +
	"\rregistered_at\x18\t \x01(\tR\fregisteredAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*e\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x02B\x16Z\x14locator/api/registryb\x06proto3"

var (
	file_api_registry_service_proto_rawDescOnce sync.Once
	file_api_registry_service_proto_rawDescData []byte
)

func file_api_registry_service_proto_rawDescGZIP() []byte {
	file_api_registry_service_proto_rawDescOnce.Do(func() {
		file_api_registry_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_registry_service_proto_rawDesc), len(file_api_registry_service_proto_rawDesc)))
	})
	return file_api_registry_service_proto_rawDescData
}

var file_api_registry_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_registry_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_registry_service_proto_goTypes = []any{
	(HealthStatus)(0),    // 0: locator.HealthStatus
	(*Endpoint)(nil),     // 1: locator.Endpoint
	(*HealthConfig)(nil), // 2: locator.HealthConfig
	(*Service)(nil),      // 3: locator.Service
	nil,                  // 4: locator.Service.MetadataEntry
}
var file_api_registry_service_proto_depIdxs = []int32{
	1, // 0: locator.HealthConfig.address:type_name -> locator.Endpoint
	1, // 1: locator.Service.address:type_name -> locator.Endpoint
	0, // 2: locator.Service.health_status:type_name -> locator.HealthStatus
	2, // 3: locator.Service.health_check:type_name -> locator.HealthConfig
	4, // 4: locator.Service.metadata:type_name -> locator.Service.MetadataEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_registry_service_proto_init() }
func file_api_registry_service_proto_init() {
	if File_api_registry_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_registry_service_proto_rawDesc), len(file_api_registry_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_registry_service_proto_goTypes,
		DependencyIndexes: file_api_registry_service_proto_depIdxs,
		EnumInfos:         file_api_registry_service_proto_enumTypes,
		MessageInfos:      file_api_registry_service_proto_msgTypes,
	}.Build()
	File_api_registry_service_proto = out.File
	file_api_registry_service_proto_goTypes = nil
	file_api_registry_service_proto_depIdxs = nil
}
