// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.30.2
// source: api/transport/transport.proto

package transport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftTransportService_Send_FullMethodName   = "/locator.RaftTransportService/Send"
	RaftTransportService_Stream_FullMethodName = "/locator.RaftTransportService/Stream"
)

// RaftTransportServiceClient is the client API for RaftTransportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftTransportServiceClient interface {
	Send(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendMessageRequest, SendMessageResponse], error)
}

type raftTransportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftTransportServiceClient(cc grpc.ClientConnInterface) RaftTransportServiceClient {
	return &raftTransportServiceClient{cc}
}

func (c *raftTransportServiceClient) Send(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, RaftTransportService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftTransportServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendMessageRequest, SendMessageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RaftTransportService_ServiceDesc.Streams[0], RaftTransportService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMessageRequest, SendMessageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftTransportService_StreamClient = grpc.BidiStreamingClient[SendMessageRequest, SendMessageResponse]

// RaftTransportServiceServer is the server API for RaftTransportService service.
// All implementations must embed UnimplementedRaftTransportServiceServer
// for forward compatibility.
type RaftTransportServiceServer interface {
	Send(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	Stream(grpc.BidiStreamingServer[SendMessageRequest, SendMessageResponse]) error
	mustEmbedUnimplementedRaftTransportServiceServer()
}

// UnimplementedRaftTransportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftTransportServiceServer struct{}

func (UnimplementedRaftTransportServiceServer) Send(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedRaftTransportServiceServer) Stream(grpc.BidiStreamingServer[SendMessageRequest, SendMessageResponse]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedRaftTransportServiceServer) mustEmbedUnimplementedRaftTransportServiceServer() {}
func (UnimplementedRaftTransportServiceServer) testEmbeddedByValue()                              {}

// UnsafeRaftTransportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftTransportServiceServer will
// result in compilation errors.
type UnsafeRaftTransportServiceServer interface {
	mustEmbedUnimplementedRaftTransportServiceServer()
}

func RegisterRaftTransportServiceServer(s grpc.ServiceRegistrar, srv RaftTransportServiceServer) {
	// If the following call panics, it indicates UnimplementedRaftTransportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftTransportService_ServiceDesc, srv)
}

func _RaftTransportService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftTransportServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftTransportService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftTransportServiceServer).Send(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftTransportService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftTransportServiceServer).Stream(&grpc.GenericServerStream[SendMessageRequest, SendMessageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftTransportService_StreamServer = grpc.BidiStreamingServer[SendMessageRequest, SendMessageResponse]

// RaftTransportService_ServiceDesc is the grpc.ServiceDesc for RaftTransportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftTransportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "locator.RaftTransportService",
	HandlerType: (*RaftTransportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _RaftTransportService_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _RaftTransportService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/transport/transport.proto",
}
