// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: api/transport/transport.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_transport_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_transport_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_transport_transport_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_api_transport_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_transport_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_transport_transport_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_transport_transport_proto protoreflect.FileDescriptor

const file_api_transport_transport_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/transport/transport.proto\x12\alocator\"(\n" +
	"\x12SendMessageRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"/\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa2\x01\n" +
	"\x14RaftTransportService\x12A\n" +
	"\x04Send\x12\x1b.locator.SendMessageRequest\x1a\x1c.locator.SendMessageResponse\x12G\n" +
	"\x06Stream\x12\x1b.locator.SendMessageRequest\x1a\x1c.locator.SendMessageResponse(\x010\x01B\x17Z\x15locator/api/transportb\x06proto3"

var (
	file_api_transport_transport_proto_rawDescOnce sync.Once
	file_api_transport_transport_proto_rawDescData []byte
)

func file_api_transport_transport_proto_rawDescGZIP() []byte {
	file_api_transport_transport_proto_rawDescOnce.Do(func() {
		file_api_transport_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_transport_transport_proto_rawDesc), len(file_api_transport_transport_proto_rawDesc)))
	})
	return file_api_transport_transport_proto_rawDescData
}

var file_api_transport_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_transport_transport_proto_goTypes = []any{
	(*SendMessageRequest)(nil),  // 0: locator.SendMessageRequest
	(*SendMessageResponse)(nil), // 1: locator.SendMessageResponse
}
var file_api_transport_transport_proto_depIdxs = []int32{
	0, // 0: locator.RaftTransportService.Send:input_type -> locator.SendMessageRequest
	0, // 1: locator.RaftTransportService.Stream:input_type -> locator.SendMessageRequest
	1, // 2: locator.RaftTransportService.Send:output_type -> locator.SendMessageResponse
	1, // 3: locator.RaftTransportService.Stream:output_type -> locator.SendMessageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_transport_transport_proto_init() }
func file_api_transport_transport_proto_init() {
	if File_api_transport_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_transport_transport_proto_rawDesc), len(file_api_transport_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_transport_transport_proto_goTypes,
		DependencyIndexes: file_api_transport_transport_proto_depIdxs,
		MessageInfos:      file_api_transport_transport_proto_msgTypes,
	}.Build()
	File_api_transport_transport_proto = out.File
	file_api_transport_transport_proto_goTypes = nil
	file_api_transport_transport_proto_depIdxs = nil
}
